name: Init Bun
description: Set up Bun and dependencies cache

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      name: Install bun

    - uses: actions/cache@v4
      name: Setup bun cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-
