name: Build and Publish

on:
  repository_dispatch:
    types: [start-scons-build]
  workflow_dispatch:
    inputs:
      scons_version:
        description: 'SCons version to build'
        required: true

jobs:
  check_scons_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check SCons version exists
        id: check_version
        run: |
          VERSION="${{ github.event.client_payload.scons_version || github.event.inputs.scons_version }}"
          if [ -z "$VERSION" ]; then
            echo "No SCons version specified"
            exit 1
          fi
          if pip install scons==$VERSION; then
            echo "scons_version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "SCons version $VERSION not found"
            exit 1
          fi

    outputs:
      scons_version: ${{ steps.check_version.outputs.scons_version }}

  build:
    needs: check_scons_version
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: scons-linux
          - os: windows-latest
            output_name: scons-win.exe
          - os: macos-latest
            output_name: scons-macos

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller scons==${{ needs.check_scons_version.outputs.scons_version }}

      - name: Build standalone SCons executable
        run: pyinstaller --add-data "$(python -c 'import scons; print(scons.__path__[0])')${{ matrix.os == 'windows-latest' && ';\scons' || ':/scons' }}" --name ${{ matrix.output_name }} src/scons_wrapper.py

      - name: Compress executable
        run: |
          cd dist
          zip -r ${{ matrix.output_name }}.zip ${{ matrix.output_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output_name }}.zip
          path: dist/${{ matrix.output_name }}.zip

  package:
    needs: [check_scons_version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Init Bun
        uses: ./.github/actions/init-bun

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Update package.json version
        run: |
          sed -i 's/"version": ".*"/"version": "${{ needs.check_scons_version.outputs.scons_version }}"/' package.json

      - name: Prepare package
        run: |
          mkdir -p package/bin
          mv dist/*/*.zip package/bin/
          cp src/run.js package/bin/scons
          chmod +x package/bin/scons
          cp package.json README.md package/

      - name: Install dependencies
        run: cd package && bun install

      - name: Publish to npm
        run: |
          cd package
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.check_scons_version.outputs.scons_version }}
          name: Release ${{ needs.check_scons_version.outputs.scons_version }}
          body: |
            This release corresponds to SCons ${{ needs.check_scons_version.outputs.scons_version }}.
            SCons Release: https://github.com/SCons/scons/releases/tag/${{ needs.check_scons_version.outputs.scons_version }}
          files: package/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
