name: Check for SCons Releases

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual triggers for testing

permissions:
  contents: write

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest SCons release
        id: get_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/SCons/scons/releases/latest)
          echo "latest_version=$(echo $LATEST_RELEASE | jq -r .tag_name)" >> $GITHUB_OUTPUT
          echo "release_url=$(echo $LATEST_RELEASE | jq -r .html_url)" >> $GITHUB_OUTPUT
          echo "release_name=$(echo $LATEST_RELEASE | jq -r .name)" >> $GITHUB_OUTPUT

      - name: Check if update is needed
        id: check_update
        run: |
          CURRENT_VERSION=$(cat .scons-version 2>/dev/null || echo "")
          if [ "${{ steps.get_release.outputs.latest_version }}" != "$CURRENT_VERSION" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update .scons-version file
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          echo "${{ steps.get_release.outputs.latest_version }}" > .scons-version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .scons-version
          git commit -m "Update SCons version to ${{ steps.get_release.outputs.latest_version }}"
          git push
